name: "testing worfklow mechanism"

on:
  push:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: testing
    steps:
      - name: Retrieve ID Token
        run: |
          ID_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.identityfederation.workers.dev" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" | jq -r '.value')
          echo $ID_TOKEN
          PAYLOAD=$(cat <<EOF
          {
          "audience": "//sts.identityfederation.workers.dev/providers/github/delegates/narwhl",
          "grantType": "urn:ietf:params:oauth:grant-type:token-exchange",
          "requestedTokenType": "urn:ietf:params:oauth:token-type:access_token",
          "scope": "https://www.googleapis.com/auth/cloud-platform",
          "subjectTokenType": "urn:ietf:params:oauth:token-type:jwt",
          "subjectToken": "${ID_TOKEN}"
          }
          EOF
          )
          echo $PAYLOAD
          curl --fail-with-body -X POST "https://sts.identityfederation.workers.dev/v1/token" \
          --header "Accept: application/json" \
          --header "Content-Type: application/json" \
          --data "${PAYLOAD}" > federated_token.json || cat federated_token.json
      - name: Set token to environment variable
        run: | 
          FEDERATED_TOKEN=$(jq -r '.access_token' federated_token.json)
          echo $FEDERATED_TOKEN

