name: "testing worfklow mechanism"

on:
  push:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    name: "testing"
    steps:
      - name: Get idtoken
        run: |
          IDTOKEN=$(curl -H "Authorization: bearer $ACTIONS_RUNTIME_TOKEN" $ACTIONS_ID_TOKEN_REQUEST_URL -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
      - name: show token
        run: echo $IDTOKEN
